on: [ push, pull_request ]

jobs:

  write-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: hello
          key: hello3

      - run: echo "Hello, world!" > hello


  read-hello:
    needs: write-hello
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: "Use GNU tar instead BSD tar"
        -if matrix.is == windows-latest
        shell: cmd
        run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
      - uses: actions/cache@v2
        with:
          path: hello
          key: hello3
