on: [ push, pull_request ]

jobs:

  A-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: gradle-7.0
          key: gradlus

      - name: Download and unzip Gradle
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://services.gradle.org/distributions/gradle-7.0-bin.zip
          unzip gradle-7.0-bin.zip


  B-gradlebundle-os:
    needs: A-gradle
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache@v2
        with:
          path: gradle-7.0
          key: gradlus

      - run: |
          echo "Check"
          du -a .
        shell: bash
