on: [ push, pull_request ]

# Plan (tiers):
# A: Prerequisites
# B: Bundle JDK and Gradle (for each target)
# C: Build stage 2 (for each target)
# D: Build gg (for each target)
# E: Build stage 1
# F: Test (for each target)
# G: Create release

name: Gradlex!
jobs:

  A-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        id: cache
        with:
          path: gradle-7.0
          key: agcache1

      - name: Download and unzip Gradle
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://services.gradle.org/distributions/gradle-7.0-bin.zip
          unzip gradle-7.0-bin.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gradle
          path: gradle-7.0

